USE TP1_2_separado
GO

-- PUNTO 1
/*1.	Pensar un ejemplo para cada tipo de relación que se puede dar entre tablas (1:1, 1:N y N:N). 
Describirlo en palabras en un comentario de SQL.

RELACION 1:1
LA FABRICACIÓN DE PRODUCTOS CUYO EMPAQUE SÓLO PUEDE SERVIR PARA CADA PRODUCTO

RELACION 1:N
LA FABRICACIÓN DE PRODUCTOS QUE PUEDEN SER DE VARIOS COLORES (REMERAS)

RELACION N:N
LA FABRICACION DE UN PRODUCTO QUE PUEDE SER DE DISTINTOS COLORES Y DISTINTOS TALLES
*/

-- PUNTO 2
/*2.	Codificar el script en lenguaje T-SQL. 
Hacer uso de restricciones de tipo Primary Key, Foreign Key, Unique, Check o las que crean necesarias.
RELACION N:N
LA FABRICACION DE UN PRODUCTO QUE PUEDE SER DE DISTINTOS COLORES Y DISTINTOS TALLES
*/

CREATE TABLE TALLES(
	ID SMALLINT NOT NULL PRIMARY KEY IDENTITY(1,1),
	NOMBRE VARCHAR(10) NOT NULL,
)
GO
ALTER TABLE PRODUCTOS
ADD CONSTRAINT FK_PR_TALLE FOREIGN KEY (ID_TALLE) REFERENCES TALLES(ID)
GO
INSERT into TALLES (NOMBRE)
values
	('S'),
	('M'),
	('L'),
	('XL'),
	('XXL')
GO
INSERT into PRODUCTOS(ID, ID_TIPO_PROD, ID_COLOR, ID_TALLE)
values
	(1,1,4,4),
	(2,2,4,4),
	(3,3,2,1),
	(4,4,3,2)
GO
